---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install dependencies"
  become: yes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - nodejs
      - npm

- name: Install pm2
  become: true
  npm:
    name: pm2
    global: yes

# - name: Create web directory
#   become: true
#   file:
#     path: "~/web"
#     state: directory

# - name: Copy index test page
#   become: true
#   copy:
#     src: index.js
#     dest: "~/web/index.js"

# - name: Start web server
#   become: true
#   command: pm2 start "~/web/index.js" -f

  #this all from chatGPT
