---
- name: Create web directory
  become: true
  file:
    path: "~/web"
    state: directory

- name: Copy artifact to remote server
  become: true
  copy:
    src: "~/artifact.tar.gz"
    dest: "~/web"
    mode: 0644

- name: Extract zipped artifact
  unarchive:
    src: ~/web/artifact.tar.gz
    dest: ~/web
    remote_src: true
    mode: 0755

- name: Install npm dependencies
  npm:
    command: install
    path: ~/web

- name: Stop default pm2 process
  command: pm2 stop default

- name: Start app with pm2
  command: pm2 start npm -- start 
  args:
    chdir: ~/web











- name: Create web directory
  become: true
  file:
    path: "~/web"
    state: directory

- name: Copy index test page
  become: true
  copy:
    src: index.js
    dest: "~/web/index.js"

- name: Start web server
  become: true
  command: pm2 start "~/web/index.js" -f

  #this all from chatGPT
