---
- name: Create web directory
  become: true
  file:
    path: "~/backend-app"
    state: directory


- name: Extract zipped artifact
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app
    remote_src: true
    mode: 0755

- name: Install npm dependencies
  npm:
    command: install
    path: ~/backend-app

- name: Stop default pm2 process
  command: pm2 stop default

- name: Start app with pm2
  command: pm2 start main.js 
  args:
    chdir: ~/backend-app/dist



- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save
